<?php
/**
 * @file
 * dealers.features.field_base.inc
 */

/**
 * Implements hook_field_default_field_bases().
 */
function dealers_field_default_field_bases() {
  $field_bases = array();

  // Exported field_base: 'field_dealers_location'.
  $field_bases['field_dealers_location'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_dealers_location',
    'indexes' => array(
      'lat' => array(
        0 => 'lat',
      ),
      'lng' => array(
        0 => 'lng',
      ),
    ),
    'locked' => 0,
    'module' => 'geolocation',
    'settings' => array(),
    'translatable' => 0,
    'type' => 'geolocation_latlng',
  );

  return $field_bases;
}
